/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author andresrosero
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    //LISTA PARA GUARDAR TAREAS
    private java.util.ArrayList<String[]> listaTareas = new java.util.ArrayList<>();
    //CARGA DE INFORMACIÓN
    private void cargarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblTareas.getModel();
    
    // Limpiar tabla
    modelo.setRowCount(0);

    // Obtener filtro seleccionado
    String filtro = cmbFiltroEstado.getSelectedItem().toString();

    // Recorrer lista
    for (String[] tarea : listaTareas) {
        String estado = tarea[1];

    // Mostrar según filtro
        if (filtro.equals("Todos") || estado.equals(filtro)) {
            modelo.addRow(tarea);
        }
    }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //AJUSTE DE LÍNEA AUTOMÁTICO EN LA DESCRIPCIÓN
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarTarea = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblListaTareas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        btnEliminarTarea = new javax.swing.JButton();
        btnCambioEstado = new javax.swing.JButton();
        cmbFiltroEstado = new javax.swing.JComboBox<>();
        lblFiltrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarTarea.setText("Agregar Tarea");
        btnAgregarTarea.addActionListener(this::btnAgregarTareaActionPerformed);

        lblBienvenida.setText("Bienvenido a ToDo");

        lblTitulo.setText("Título:");

        txtTitulo.addActionListener(this::txtTituloActionPerformed);

        lblDescripcion.setText("Descripción:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        lblEstado.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En progreso", "Completada" }));

        lblListaTareas.setText("Lista de Tareas:");

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Estado"
            }
        ));
        tblTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTareasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTareas);

        btnEliminarTarea.setText("Eliminar Tarea");
        btnEliminarTarea.addActionListener(this::btnEliminarTareaActionPerformed);

        btnCambioEstado.setText("Cambiar Estado");
        btnCambioEstado.addActionListener(this::btnCambioEstadoActionPerformed);

        cmbFiltroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pendiente", "En progreso", "Completada" }));
        cmbFiltroEstado.addActionListener(this::cmbFiltroEstadoActionPerformed);

        lblFiltrar.setText("Filtrar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCambioEstado)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTarea)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarTarea))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBienvenida)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addGap(44, 44, 44)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEstado))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblListaTareas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblListaTareas)
                        .addComponent(lblFiltrar))
                    .addComponent(cmbFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTarea)
                    .addComponent(btnEliminarTarea)
                    .addComponent(btnCambioEstado))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
        // TODO add your handling code here:
        String titulo = txtTitulo.getText();
        String estado = cmbEstado.getSelectedItem().toString();

        // VALIDACIÓN TITULO OBLIGATORIO
        if (titulo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El título es obligatorio");
        return;
        }
        // AGREGAR TAREAS A LA TABLA
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblTareas.getModel();
        listaTareas.add(new String[]{titulo, estado});//Para manejo de datos
        // Anterior sin guardado modelo.addRow(new Object[]{titulo, estado}); //Visual en la tabla
        cargarTabla();

        // LIMPIAR CAMPOS
        txtTitulo.setText("");
        txtDescripcion.setText("");
        cmbEstado.setSelectedIndex(0);
    }//GEN-LAST:event_btnAgregarTareaActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed
        // TODO add your handling code here:
        //VALIDACION SIN DATOS
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblTareas.getModel();

        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Aún no se ha creado una tarea");
        return;
        }
        
        int fila = tblTareas.getSelectedRow();
        // VALIDACIÓN DE TAREA SELECCIONADA
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una tarea para eliminar");
        return;
        }

        // PREGUNTAR TITULO DE LA TAREA
        String titulo = modelo.getValueAt(fila, 0).toString();

        // DUALIDAD DE LA ELIMINACIÓN DE LA TAREA SELECCIONADA
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Eliminará la tarea: " + titulo + "\n¿Desea continuar?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        // CONFIRMACIÓN DE TAREA ELIMINADA
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            listaTareas.remove(fila);
            cargarTabla();
        }
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnCambioEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioEstadoActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblTareas.getModel();
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Aún no se ha creado una tarea");
        return;
        }
        
        int fila = tblTareas.getSelectedRow();
        // VALIDACIÓN TAREA SELECCIONADA
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una tarea");
        return;
        }
        // OBTENER ESTADO DEL COMBO BOTON
        String nuevoEstado = cmbEstado.getSelectedItem().toString();
        // ACTUALIZAR TABLA
        listaTareas.get(fila)[1] = nuevoEstado;
        cargarTabla();
    }//GEN-LAST:event_btnCambioEstadoActionPerformed

    private void tblTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTareasMouseClicked
        // TODO add your handling code here:
        int fila = tblTareas.getSelectedRow();
        if (fila != -1) {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblTareas.getModel();
            String estado = modelo.getValueAt(fila, 1).toString();
            cmbEstado.setSelectedItem(estado);
        }
    }//GEN-LAST:event_tblTareasMouseClicked

    private void cmbFiltroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroEstadoActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_cmbFiltroEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnCambioEstado;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFiltroEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblListaTareas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblTareas;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
